# GitHub Actions workflow for collecting and uploading test coverage
# Adds a step to generate and upload coverage reports using actions/upload-artifact

name: Build, Test, and Release Obsidian Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm test -- --coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - name: Build plugin
        run: npm run build
      - name: Check required files
        run: |
          test -f main.js
          test -f manifest.json
          test -f README.md
          test -f LICENSE

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
